### ISSUE TITLE
DockitCCShowcases still display multiple boxes

### ISSUE THREAD

**Issue by m4dz** [divriots/dockit-core#31]
Demos here: https://backlight.dev/edit/Tve1ObNsVqRX7NlkUnzD/colors/doc/index.md?p=doc

Boxes should display only one block, not two.

<img width="908" alt="Screenshot 2021-12-17 at 17 08 29" src="https://user-images.githubusercontent.com/471486/146573896-0f3a09e8-8692-4d95-aacc-1c1ae265b057.png">

**Comment by bashmish** [comment]
@m4dz I think I fixed this at some point, can't find where exactly. Closing. Feel free to reopen if you have a new repro, because the current one doesn't work.
